### ISSUE TITLE
fluidsynth 2.1.3 can't find pa_threaded_mainloop_get_api symbol

### ISSUE THREAD

**Issue by mariuszkurek** [i-rinat/apulse#113]
I'm using latest alibpulse from Arch User Repository (not really sure if it's supported, but it builds without patches, just installs in different location, so I assume it is). Whenever I start fluidsynth, I get an error:
`fluidsynth: symbol lookup error: /usr/lib/libpulse-simple.so.0: undefined symbol: pa_threaded_mainloop_get_api`

**Comment by i-rinat** [comment]
Hi.
I think that's what was fixed by https://github.com/i-rinat/apulse/pull/101. `libpulse-simple.so` uses symbols from `libpulse.so`, but wasn't linked with it.

Looks like AUR currently has version `0.1.12`, but the fix mentioned was made after 0.1.12. There is already 0.1.13, it should have that issue fixed.

**Comment by mariuszkurek** [comment]
That was the case indeed, thanks!
