### ISSUE TITLE
sound in skype stops working right after the launch sound

### ISSUE THREAD

**Issue by l29ah** [i-rinat/apulse#38]
It writes to the console just after the sound ends:

```
ALSA lib /var/tmp/paludis/media-libs-alsa-lib-1.1.1/work/alsa-lib-1.1.1/src/pcm/pcm_dsnoop.c:654:(snd_pcm_dsnoop_open) unable to open slave
[apulse] [error] do_connect_pcm, snd_pcm_open, Дескриптор файла в плохом состоянии
[apulse] [error] do_connect_pcm, snd_pcm_open, Дескриптор файла в плохом состоянии
```

I'm using apulse-0.1.7 with skype-4.3.0.37 in Gentoo.

**Comment by l29ah** [comment]
But somehow it works if i try lauching it while `mumble` is working.

**Comment by h1z1** [comment]
What does your asoundrc look like?  Are you sure mumble is using pulse and not alsa directly?

**Comment by i-rinat** [comment]
Hello. I've just realized that I heard about issues with `apulse` with alsa-lib of version 1.1.1 while downgrading alsa-lib 1.1.0 solved that.

I think there is something wrong with shared memory segment created by alsa-lib for sound mixing. But I can't reproduce issue on my machine, and thus cannot debug it.

**Comment by h1z1** [comment]
latest version for CentOS 7.0 is 1.0.28

Only problems with shm I've ever run into were because of ipc_key'n friends.  .. and pulseaudio updates breaking everything.   I suspect the comment from Axiomatic- on Bug #222 for Palemoon has more implications (https://github.com/MoonchildProductions/Pale-Moon/issues/222).

Another problem I had was some applications link against specific versions of libpulse-mainloop-glib.  Created symlinks for now, seems to work.  At some point I need to look at why rpm targets don't work with cmake and add pulse so it's never updated again, but it's a manual build for now.  64 & 32 bit.

**Comment by ismaell** [comment]
Nothing to do with dmix/dsnoop, I'm trying to use hw devices and am experiencing the problem.

**Comment by ismaell** [comment]
Problem identified, it's an ALSA initialization race-condition, between two threads, due to a bug in alsa-lib.

Fix coming soon.

So, as @l29ah mentions, the race condition can't occur if another application is already using the ALSA device.

**Comment by ismaell** [comment]
It's actually two bugs, one in alsa-lib, the other a limitation of apulse.

**Comment by i-rinat** [comment]
> the other a limitation of apulse.

Is it something I can fix? Or it's an inherent limitation of the way it's implemented?

**Comment by ismaell** [comment]
> Is it something I can fix? Or it's an inherent limitation of the way it's implemented?

It's fixable, but not trivial. I should explain...

Applications are often not prepared to recover from PA failures; application's fault, no doubt, but for this reason, hardware failures shouldn't translate into PA request failures.

The problem is, apulse doesn't behave like PA, it passes ALSA/HW errors along, while PA keeps applications isolated from that.

So, some redesign is in order.

**Comment by i-rinat** [comment]
> The problem is, apulse doesn't behave like PA, it passes ALSA/HW errors along, while PA keeps applications isolated from that.

Thanks. I didn't thought about that.

**Comment by ismaell** [comment]
`alsa-lib` commit `7640856769d2d687877df720af5ef1ecd8938888 ("pcm: Fix shm initialization race-condition")` fixes this issue.

**Comment by ismaell** [comment]
@i-rinat ping. Shouldn't this be closed?

**Comment by i-rinat** [comment]
> Shouldn't this be closed?

Yeah, it probably should. I couldn't verify the fix since I hadn't the bug triggering on my machine. And now it's no longer reproducible anyway, as Skype 4.3 stopped working for good.

Thank you for notifying.
