### ISSUE TITLE
Lag between audio and video when playing video in firefox-53 using apulse-0.1.9

### ISSUE THREAD

**Issue by powerman** [i-rinat/apulse#51]
The lag is small and thus hard to measure and prove, but looks like at least two people [noticed it](https://bugs.gentoo.org/show_bug.cgi?id=616512#c5), so I decide to open issue here anyway - either @i-rinat may have an idea how to debug/fix it or more people will notice it too and report here more details which may helps fixing it.

**Comment by i-rinat** [comment]
This is most probably related to latency handling. Since PulseAudio API is designed to be remote, it has latency estimation here and there. I actually had no idea how to calculate it, so there are some arbitrary numbers currently.

The first point to look at is `/src/apulse-context.c`. Search for string `latency = 100000`, there should be four places. I'd try to decrease the values (the are in microseconds) to, say, 10000 us as a start.

Again, I currently have no idea how to do this in a correct way. Some additional research on PA API is required.

**Comment by i-rinat** [comment]
I stumbled upon the video test for audio sync: https://www.youtube.com/watch?v=ucZl6vQ_8Uo.

Looks like on my machine, audio is synchronized just fine when using Firefox + apulse.

**Comment by powerman** [comment]
I've no idea is it still actual, but it's anyway too outdated and can be closed.
