### ISSUE TITLE
Firefox 59 made it stop working again

### ISSUE THREAD

**Issue by hishamhm** [i-rinat/apulse#81]
Looks like since the latest update (59.0), Firefox stopped working with apulse again.

When one opens a site with audio (e.g. youtube.com), Firefox now shows a notification bar saying "To play audio, you may need to install the required PulseAudio software." I suppose they added some new detection code.

I tried both apulse 0.1.11 and the latest `master` on git. Prior to Firefox 59 I had it working. I have the necessary entries in `about:config`: `security.sandbox.content.syscall_whitelist` set to `16` (x86_64) and `security.sandbox.content.write_path_whitelist` set to `/dev/snd`

**Comment by i-rinat** [comment]
I think it's the sandboxing again. When I do test runs, I have binaries not in `/usr/lib` but in other directory instead. And Firefox refuses to load them unless I add the path to the `security.sandbox.content.read_path_whitelist` setting. Since GoboLinux uses non-standard paths, this may be the cause of the issue.

Also, trailing slash there is important. For example, for `/dev/snd` and all files in it to be whitelisted, one must use `/dev/snd/`, not just `/dev/snd`.

And... looks like `master` branch is broken. I'm going to revert last two commits until I figure out what went wrong. However, `v0.1.11` should be fine.

**Comment by hishamhm** [comment]
@i-rinat Thank you! Indeed it was the tightened sandboxing and the unusual paths.

I relaunched Firefox with the `MOZ_SANDBOX_LOGGING=1` environment variable, and I added the paths for which it reported path denials, and now sound is working againg with 0.1.11!

For reference, this is what my `about:config` settings look like on GoboLinux now:
* `security.sandbox.content.read_path_whitelist` = `/dev/snd/,/Programs/APulse/,/Programs/ORC/,/usr/local/lib/`
* `security.sandbox.content.write_path_whitelist` = `/dev/snd/`
* `security.sandbox.content.syscall_whitelist` = `16`

Thank you once again!
