### ISSUE TITLE
Apulse does not work with dmix

### ISSUE THREAD

**Issue by susobaco** [i-rinat/apulse#85]
Hi, I noticed that when using abrowser (firefox) it doesn't allow you to use another audio playback program. The console output is as follows:

APULSE_PLAYBACK_DEVICE=dmix apulse abrowser

_[apulse] [error] do_connect_pcm: can't set sample format 14 ("FLOAT_LE") for playback device "dmix". Error code -22 (Argumento inválido)
[apulse] [error] do_connect_pcm: failed to open ALSA device. Apulse does no resampling or format conversion, leaving that task to ALSA plugins. Ensure that selected device is capable of playing a particular sample format at a particular rate. They have to be supported by either hardware directly, or by "plug" and "dmix" ALSA plugins which will perform required conversions on CPU._

More information:
dpkg -s alsa-base | grep Version
Version: 1.0.25+dfsg-0ubuntu5
dpkg -s abrowser | grep Version
Version: 59.0.2+build1-0ubuntu0.16.04.3+8.0trisquel56

Distribution, Trisquel Flidas based in ubuntu xenial

latest version of apulse.
need more information?
Thank you

**Comment by susobaco** [comment]
Thanks for the answer. The problem is that when I open abrowser with apulse, it does not work with dmix, as I try to open audacious or vlc and it gives me a device opening error message, as it is busy. If I open audacious and vlc first, no problem, but apulse abrowser, it doesn't sound. I've tried what you said, and it's the same thing.

**Comment by i-rinat** [comment]
What about device called `default`? Did you try it?

Do you have any custom ALSA configuration (`.asoundrc`)?

**Comment by susobaco** [comment]
I have already done all the tests, with an asoundrc with dmix, without asoundrc, and the same problem continues

**Comment by i-rinat** [comment]
> I guess Firefox changed the sound format they're feeding to PulseAudio?

Don't think so. As long as I remember, Firefox used float32 samples. Maybe something have changed in ALSA libraries?

> my setup stopped working this week again

Haven't checked yet, but could it be more strict sandbox that doesn't allow reading files from `/usr/share/alsa` anymore? That could explain why you are trying to specify ALSA device directly rather that relying on implicit `default`.

**Comment by susobaco** [comment]
These are the results:
mpv --audio-device=plug/dmix Alien\ Nation\ El\ legado\ Uldara.avi
Playing: Alien Nation El legado Uldara.avi
 (+) Video --vid=1 (mpeg4)
 (+) Audio --aid=1 (mp3)
     Audio --aid=2 (mp3)
[ao] Audio output plug not found!
[ao] Failed to initialize audio driver 'plug'
[ao] This audio driver/device was forced with the --audio-device option.
[ao] Try unsetting it.
Could not open/initialize audio device -> no sound.
Audio: no audio

 mpv --audio-device=alsa/dmix Alien\ Nation\ El\ legado\ Uldara.avi
Playing: Alien Nation El legado Uldara.avi
 (+) Video --vid=1 (mpeg4)
 (+) Audio --aid=1 (mp3)
     Audio --aid=2 (mp3)
AO: [alsa] 48000Hz stereo 2ch s32
VO: [opengl] 560x416 yuv420p
AV: 00:00:23 / 01:26:07 (0%) A-V:  0.000

I don't know what's wrong with me, my plug device doesn't work?

**Comment by i-rinat** [comment]
> I don't know what's wrong with me, my plug device doesn't work?

That's OK, since you were just asking `mpv` to output audio through driver `plug`. It has no such driver, but has `alsa` for ALSA and `pulse` for PulseAudio.

If you want to play sound through `plug` device in ALSA, you need to use
```
mpv --audio-device=alsa/plug audio.ogg
```
But rather using `plug`, you'd probably want to use `plug:dmix`:
```
mpv --audio-device=alsa/plug:dmix audio.ogg
```
Here is why. `dmix` is a mixing device. It attaches to `hw`, which only supports what your hardware directly supports. `dmix` itself doesn't convert sample formats, so if you want to play float32 samples, but your hardware supports only signed 16-bit integers, it won't work. That's where `plug` comes to the rescue. It converts whatever you give it to the format of whatever you connected it to.

Looks like browser you are trying to use tries to output float32 samples through PulseAudio. When you are using apulse, it sees the format (FLOAT_LE) and asks ALSA for the same format. Then, if you are using `plug:dmix`, `plug` converts float32 to signed 16-bit integers, passes it to `dmix`. `dmix` mixes multiple streams (if there are multiple streams), and passes 16-bit integers to the hardware. Hardware generates actual voltage that drives actual speakers.

**Comment by susobaco** [comment]
Perfect, with this command, it works. Thank you very much.
APULSE_PLAYBACK_DEVICE=plug:dmix apulse abrowser
