### ISSUE TITLE
apulse does not work with the snap version of Firefox

### ISSUE THREAD

**Issue by baptx** [i-rinat/apulse#95]
After having installed Firefox as a snap package with the command "snap install firefox", if I try to run "apulse firefox", I don't get any sound on YouTube. To get sound, I have to bypass the sandbox by directly calling "apulse /snap/firefox/137/firefox" (but then I cannot use my Firefox profile located in the folder ~/snap/firefox/). I am not sure if this can be fixed on the apulse side or if it should be fixed by the snapd program.

**Comment by i-rinat** [comment]
As far as I know, Snap packages are using (compressed) filesystem image. There are not only application itself, but all the libraries it depends on. That's why the same package works on various versions of Ubuntu. And there is `libpulse.so.0` → `libpulse.so.0.19.0` in the Firefox Snap package. So, it uses that instead of any other library from your OS.

I don't think it can be "fixed", as it's exactly what Snap was built for — to make applications self-consistent.

**Comment by baptx** [comment]
Ok, so there is no way to hack and use ALSA instead of PulseAudio with the Firefox Snap package?
Maybe if apulse is directly called inside of the Snap filesystem image?

**Comment by i-rinat** [comment]
> Ok, so there is no way to hack and use ALSA instead of PulseAudio with the Firefox Snap package?

I don't think it's possible.

> Maybe if apulse is directly called inside of the Snap filesystem image?

If one replaces `libpulse.so.0` from PulseAudio by `libpulse.so.0` from apulse, I would expect that to work. But then you'll need to repack snap package, and probably, to sign it again. After all that work, it's not so much harder to go further, and to build Firefox from source code with ALSA enabled.
